// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result } from 'dedot/codecs';
import type {
  GenericConstructorQuery,
  GenericConstructorQueryCall,
  GenericConstructorCallResult,
  ConstructorCallOptions,
  ContractInstantiateResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ConstructorQuery<Type extends MetadataType> extends GenericConstructorQuery<Type> {
  /**
   * Constructor that initializes the `bool` value to the given `init_value`.
   *
   * @param {boolean} initValue
   * @param {ConstructorCallOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorQueryCall<
    (
      initValue: boolean,
      options?: ConstructorCallOptions,
    ) => Promise<GenericConstructorCallResult<[], ContractInstantiateResult>>,
    Type
  >;
}
