// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160 } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {
  /**
   * Event emitted when the flipper value is flipped
   *
   *
   **/
  Flipped: GenericContractEvent<
    'Flipped',
    {
      /**
       * The old value before flipping
       *
       * @indexed: false
       **/
      oldValue: boolean;
      /**
       * The new value after flipping
       *
       * @indexed: false
       **/
      newValue: boolean;
      /**
       * The account that triggered the flip
       *
       * @indexed: true
       **/
      caller: H160;
    },
    Type
  >;
}
