// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type { InkPrimitivesLangError } from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * A message that can be called on instantiated contracts.
   * This one flips the value of the stored `bool` from `true`
   * to `false` and vice versa.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x633aa551
   **/
  flip: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult>>,
    Type
  >;

  /**
   * Simply returns the current value of our `bool`.
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x2f865bd9
   **/
  get: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult>>,
    Type
  >;
}
