// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ContractTx<Type extends MetadataType> extends GenericContractTx<Type> {
  /**
   * A message that can be called on instantiated contracts.
   * This one flips the value of the stored `bool` from `true`
   * to `false` and vice versa.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x633aa551
   **/
  flip: GenericContractTxCall<(options?: ContractTxOptions) => ContractSubmittableExtrinsic, Type>;
}
