// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericConstructorTx,
  GenericConstructorTxCall,
  ConstructorTxOptions,
  InkGenericContractApi,
  GenericInstantiateSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';

export interface ConstructorTx<
  ContractApi extends InkGenericContractApi,
  Type extends MetadataType,
> extends GenericConstructorTx<Type> {
  /**
   * Constructor - initializes with token_id counter at 0
   *
   * @param {ConstructorTxOptions} options
   *
   * @selector 0x9bae9d5e
   **/
  new: GenericConstructorTxCall<
    (options?: ConstructorTxOptions) => GenericInstantiateSubmittableExtrinsic<ContractApi>,
    Type
  >;
}
