// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { H160, FixedBytes } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent, MetadataType } from 'dedot/contracts';

export interface ContractEvents<Type extends MetadataType> extends GenericContractEvents<Type> {
  /**
   *
   *
   **/
  ApprovalForAll: GenericContractEvent<
    'ApprovalForAll',
    {
      /**
       *
       * @indexed: true
       **/
      owner: H160;
      /**
       *
       * @indexed: true
       **/
      operator: H160;
      /**
       *
       * @indexed: false
       **/
      approved: boolean;
    },
    Type
  >;

  /**
   * Emitted when a passport is revoked
   *
   *
   **/
  PassportRevoked: GenericContractEvent<
    'PassportRevoked',
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: bigint;
      /**
       *
       * @indexed: true
       **/
      issuer: H160;
      /**
       *
       * @indexed: false
       **/
      reason: string | undefined;
      /**
       *
       * @indexed: false
       **/
      revokedAt: number;
    },
    Type
  >;

  /**
   * Emitted when a passport dataset is updated
   *
   *
   **/
  PassportUpdated: GenericContractEvent<
    'PassportUpdated',
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: bigint;
      /**
       *
       * @indexed: false
       **/
      datasetUri: string;
      /**
       *
       * @indexed: false
       **/
      payloadHash: FixedBytes<32>;
      /**
       *
       * @indexed: false
       **/
      datasetType: string;
      /**
       *
       * @indexed: false
       **/
      version: number;
      /**
       *
       * @indexed: false
       **/
      updatedAt: number;
    },
    Type
  >;

  /**
   * Emitted when a passport is registered
   *
   *
   **/
  PassportRegistered: GenericContractEvent<
    'PassportRegistered',
    {
      /**
       *
       * @indexed: true
       **/
      tokenId: bigint;
      /**
       *
       * @indexed: true
       **/
      issuer: H160;
      /**
       *
       * @indexed: false
       **/
      datasetUri: string;
      /**
       *
       * @indexed: false
       **/
      payloadHash: FixedBytes<32>;
      /**
       *
       * @indexed: false
       **/
      datasetType: string;
      /**
       *
       * @indexed: false
       **/
      version: number;
      /**
       *
       * @indexed: false
       **/
      createdAt: number;
    },
    Type
  >;

  /**
   *
   *
   **/
  Approval: GenericContractEvent<
    'Approval',
    {
      /**
       *
       * @indexed: true
       **/
      owner: H160;
      /**
       *
       * @indexed: true
       **/
      approved: H160;
      /**
       *
       * @indexed: true
       **/
      tokenId: bigint;
    },
    Type
  >;

  /**
   *
   *
   **/
  Transfer: GenericContractEvent<
    'Transfer',
    {
      /**
       *
       * @indexed: true
       **/
      from: H160 | undefined;
      /**
       *
       * @indexed: true
       **/
      to: H160 | undefined;
      /**
       *
       * @indexed: true
       **/
      tokenId: bigint;
    },
    Type
  >;
}
