// Generated by dedot cli

import type { GenericSubstrateApi, RpcVersion, RpcV2 } from 'dedot/types';
import type { InkGenericContractApi, WithLazyStorage } from 'dedot/contracts';
import type { SubstrateApi } from 'dedot/chaintypes';
import type { InkPrimitivesLangError, DppContractDppContractV2 } from './types.js';
import { ContractQuery } from './query.js';
import { ContractTx } from './tx.js';
import { ConstructorQuery } from './constructor-query.js';
import { ConstructorTx } from './constructor-tx.js';
import { ContractEvents } from './events.js';

export * from './types.js';

/**
 * @name: DppContractContractApi
 * @contractName: dpp_contract
 * @contractVersion: 6.0.0
 * @authors: FIDES-DPP
 * @language: ink! 6.0.0-beta
 **/
export interface DppContractContractApi<
  ChainApi extends GenericSubstrateApi = SubstrateApi,
> extends InkGenericContractApi<ChainApi> {
  metadataType: 'ink';
  query: ContractQuery<'ink'>;
  tx: ContractTx<'ink'>;
  constructorQuery: ConstructorQuery<'ink'>;
  constructorTx: ConstructorTx<DppContractContractApi, 'ink'>;
  events: ContractEvents<'ink'>;
  storage: {
    root(): Promise<DppContractDppContractV2>;
    lazy(): WithLazyStorage<DppContractDppContractV2>;
  };

  types: {
    ChainApi: ChainApi;
    RootStorage: DppContractDppContractV2;
    LazyStorage: WithLazyStorage<DppContractDppContractV2>;
    LangError: InkPrimitivesLangError;
  };
}
