// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { FixedBytes, Result } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
  MetadataType,
} from 'dedot/contracts';
import type {
  DppContractDppContractV2Granularity,
  DppContractDppContractV2Error,
  InkPrimitivesLangError,
  DppContractDppContractV2PassportRecord,
} from './types.js';

export interface ContractQuery<Type extends MetadataType> extends GenericContractQuery<Type> {
  /**
   * Register a new passport
   *
   * Creates a new passport record with the provided anchor data.
   *
   * # Arguments
   *
   * * `dataset_uri` - IPFS URI (e.g., "ipfs://bafkrei...")
   * * `payload_hash` - SHA-256 hash of the JWT string
   * * `dataset_type` - MIME type (e.g., "application/vc+jwt")
   * * `granularity` - Granularity level (ProductClass, Batch, or Item)
   * * `subject_id_hash` - Optional hashed canonical subject identifier
   *
   * # Returns
   *
   * Token ID of the newly registered passport
   *
   * # Errors
   *
   * * `InvalidInput` - Empty dataset_uri or dataset_type
   *
   * @param {string} datasetUri
   * @param {FixedBytes<32>} payloadHash
   * @param {string} datasetType
   * @param {DppContractDppContractV2Granularity} granularity
   * @param {FixedBytes<32> | undefined} subjectIdHash
   * @param {ContractCallOptions} options
   *
   * @selector 0x50bc73be
   **/
  registerPassport: GenericContractQueryCall<
    (
      datasetUri: string,
      payloadHash: FixedBytes<32>,
      datasetType: string,
      granularity: DppContractDppContractV2Granularity,
      subjectIdHash: FixedBytes<32> | undefined,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<bigint, DppContractDppContractV2Error>, ContractCallResult>>,
    Type
  >;

  /**
   * Get passport record by token ID
   *
   * # Arguments
   *
   * * `token_id` - Token ID to retrieve
   *
   * # Returns
   *
   * PassportRecord if found, None otherwise
   *
   * @param {bigint} tokenId
   * @param {ContractCallOptions} options
   *
   * @selector 0x0ea9786c
   **/
  getPassport: GenericContractQueryCall<
    (
      tokenId: bigint,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<DppContractDppContractV2PassportRecord | undefined, ContractCallResult>>,
    Type
  >;

  /**
   * Update dataset (new version on IPFS)
   *
   * Updates the IPFS reference and increments version.
   * Only the original issuer can call this.
   *
   * # Arguments
   *
   * * `token_id` - Token ID to update
   * * `dataset_uri` - New IPFS URI
   * * `payload_hash` - New SHA-256 hash
   * * `dataset_type` - New MIME type
   * * `subject_id_hash` - New optional subject ID hash
   *
   * # Notes
   *
   * Granularity is IMMUTABLE after registration. If you need to change
   * granularity, revoke the old passport and register a new one.
   *
   * # Errors
   *
   * * `TokenNotFound` - Token ID doesn't exist
   * * `Unauthorized` - Caller is not the issuer
   * * `PassportRevoked` - Cannot update revoked passport
   * * `InvalidInput` - Empty dataset_uri or dataset_type
   *
   * @param {bigint} tokenId
   * @param {string} datasetUri
   * @param {FixedBytes<32>} payloadHash
   * @param {string} datasetType
   * @param {FixedBytes<32> | undefined} subjectIdHash
   * @param {ContractCallOptions} options
   *
   * @selector 0x25a2795e
   **/
  updateDataset: GenericContractQueryCall<
    (
      tokenId: bigint,
      datasetUri: string,
      payloadHash: FixedBytes<32>,
      datasetType: string,
      subjectIdHash: FixedBytes<32> | undefined,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], DppContractDppContractV2Error>, ContractCallResult>>,
    Type
  >;

  /**
   * Revoke a passport (irreversible)
   *
   * Sets status to Revoked. Cannot be undone.
   * Only the original issuer can call this.
   *
   * # Arguments
   *
   * * `token_id` - Token ID to revoke
   * * `reason` - Optional revocation reason (stored in event only)
   *
   * # Errors
   *
   * * `TokenNotFound` - Token ID doesn't exist
   * * `Unauthorized` - Caller is not the issuer
   * * `AlreadyRevoked` - Passport is already revoked
   *
   * @param {bigint} tokenId
   * @param {string | undefined} reason
   * @param {ContractCallOptions} options
   *
   * @selector 0xa4cec762
   **/
  revokePassport: GenericContractQueryCall<
    (
      tokenId: bigint,
      reason: string | undefined,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], DppContractDppContractV2Error>, ContractCallResult>>,
    Type
  >;

  /**
   * Get next token ID (for informational purposes)
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x4bb70b15
   **/
  nextTokenId: GenericContractQueryCall<
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<bigint, ContractCallResult>>,
    Type
  >;
}
