// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { FixedBytes } from 'dedot/codecs';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
  MetadataType,
} from 'dedot/contracts';
import type { DppContractDppContractV2Granularity } from './types.js';

export interface ContractTx<Type extends MetadataType> extends GenericContractTx<Type> {
  /**
   * Register a new passport
   *
   * Creates a new passport record with the provided anchor data.
   *
   * # Arguments
   *
   * * `dataset_uri` - IPFS URI (e.g., "ipfs://bafkrei...")
   * * `payload_hash` - SHA-256 hash of the JWT string
   * * `dataset_type` - MIME type (e.g., "application/vc+jwt")
   * * `granularity` - Granularity level (ProductClass, Batch, or Item)
   * * `subject_id_hash` - Optional hashed canonical subject identifier
   *
   * # Returns
   *
   * Token ID of the newly registered passport
   *
   * # Errors
   *
   * * `InvalidInput` - Empty dataset_uri or dataset_type
   *
   * @param {string} datasetUri
   * @param {FixedBytes<32>} payloadHash
   * @param {string} datasetType
   * @param {DppContractDppContractV2Granularity} granularity
   * @param {FixedBytes<32> | undefined} subjectIdHash
   * @param {ContractTxOptions} options
   *
   * @selector 0x50bc73be
   **/
  registerPassport: GenericContractTxCall<
    (
      datasetUri: string,
      payloadHash: FixedBytes<32>,
      datasetType: string,
      granularity: DppContractDppContractV2Granularity,
      subjectIdHash: FixedBytes<32> | undefined,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Update dataset (new version on IPFS)
   *
   * Updates the IPFS reference and increments version.
   * Only the original issuer can call this.
   *
   * # Arguments
   *
   * * `token_id` - Token ID to update
   * * `dataset_uri` - New IPFS URI
   * * `payload_hash` - New SHA-256 hash
   * * `dataset_type` - New MIME type
   * * `subject_id_hash` - New optional subject ID hash
   *
   * # Notes
   *
   * Granularity is IMMUTABLE after registration. If you need to change
   * granularity, revoke the old passport and register a new one.
   *
   * # Errors
   *
   * * `TokenNotFound` - Token ID doesn't exist
   * * `Unauthorized` - Caller is not the issuer
   * * `PassportRevoked` - Cannot update revoked passport
   * * `InvalidInput` - Empty dataset_uri or dataset_type
   *
   * @param {bigint} tokenId
   * @param {string} datasetUri
   * @param {FixedBytes<32>} payloadHash
   * @param {string} datasetType
   * @param {FixedBytes<32> | undefined} subjectIdHash
   * @param {ContractTxOptions} options
   *
   * @selector 0x25a2795e
   **/
  updateDataset: GenericContractTxCall<
    (
      tokenId: bigint,
      datasetUri: string,
      payloadHash: FixedBytes<32>,
      datasetType: string,
      subjectIdHash: FixedBytes<32> | undefined,
      options?: ContractTxOptions,
    ) => ContractSubmittableExtrinsic,
    Type
  >;

  /**
   * Revoke a passport (irreversible)
   *
   * Sets status to Revoked. Cannot be undone.
   * Only the original issuer can call this.
   *
   * # Arguments
   *
   * * `token_id` - Token ID to revoke
   * * `reason` - Optional revocation reason (stored in event only)
   *
   * # Errors
   *
   * * `TokenNotFound` - Token ID doesn't exist
   * * `Unauthorized` - Caller is not the issuer
   * * `AlreadyRevoked` - Passport is already revoked
   *
   * @param {bigint} tokenId
   * @param {string | undefined} reason
   * @param {ContractTxOptions} options
   *
   * @selector 0xa4cec762
   **/
  revokePassport: GenericContractTxCall<
    (tokenId: bigint, reason: string | undefined, options?: ContractTxOptions) => ContractSubmittableExtrinsic,
    Type
  >;
}
