// Generated by dedot cli

import type { H160, FixedBytes } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type DppContractDppContractV2PassportRecord = {
  tokenId: bigint;
  issuer: H160;
  datasetUri: string;
  payloadHash: FixedBytes<32>;
  datasetType: string;
  version: number;
  status: DppContractDppContractV2PassportStatus;
  createdAt: number;
  updatedAt: number;
  granularity: DppContractDppContractV2Granularity;
  subjectIdHash?: FixedBytes<32> | undefined;
};

export type DppContractDppContractV2PassportStatus = 'Draft' | 'Active' | 'Suspended' | 'Revoked' | 'Archived';

export type DppContractDppContractV2Granularity = 'ProductClass' | 'Batch' | 'Item';

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type DppContractDppContractV2 = {
  passports: { get(arg: bigint): Promise<DppContractDppContractV2PassportRecord | undefined> };
  nextTokenId: bigint;
};

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type DppContractDppContractV2Error =
  | 'TokenNotFound'
  | 'InvalidInput'
  | 'Unauthorized'
  | 'PassportRevoked'
  | 'AlreadyRevoked';
